/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const ORACLE_ACCOUNT_DISCRIMINATOR = new Uint8Array([
  189, 23, 49, 197, 79, 96, 245, 91,
]);

export function getOracleAccountDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    ORACLE_ACCOUNT_DISCRIMINATOR,
  );
}

export type OracleAccount = {
  discriminator: ReadonlyUint8Array;
  authority: Address;
  value: bigint;
  lastUpdated: bigint;
};

export type OracleAccountArgs = {
  authority: Address;
  value: number | bigint;
  lastUpdated: number | bigint;
};

/** Gets the encoder for {@link OracleAccountArgs} account data. */
export function getOracleAccountEncoder(): FixedSizeEncoder<OracleAccountArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["authority", getAddressEncoder()],
      ["value", getU64Encoder()],
      ["lastUpdated", getI64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: ORACLE_ACCOUNT_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link OracleAccount} account data. */
export function getOracleAccountDecoder(): FixedSizeDecoder<OracleAccount> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["authority", getAddressDecoder()],
    ["value", getU64Decoder()],
    ["lastUpdated", getI64Decoder()],
  ]);
}

/** Gets the codec for {@link OracleAccount} account data. */
export function getOracleAccountCodec(): FixedSizeCodec<
  OracleAccountArgs,
  OracleAccount
> {
  return combineCodec(getOracleAccountEncoder(), getOracleAccountDecoder());
}

export function decodeOracleAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<OracleAccount, TAddress>;
export function decodeOracleAccount<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<OracleAccount, TAddress>;
export function decodeOracleAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<OracleAccount, TAddress> | MaybeAccount<OracleAccount, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getOracleAccountDecoder(),
  );
}

export async function fetchOracleAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<OracleAccount, TAddress>> {
  const maybeAccount = await fetchMaybeOracleAccount(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeOracleAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<OracleAccount, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeOracleAccount(maybeAccount);
}

export async function fetchAllOracleAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<OracleAccount>[]> {
  const maybeAccounts = await fetchAllMaybeOracleAccount(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeOracleAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<OracleAccount>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeOracleAccount(maybeAccount));
}

export function getOracleAccountSize(): number {
  return 56;
}
