/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  type ParsedCreateOracleAccountInstruction,
  type ParsedInitializeInstruction,
  type ParsedUpdateOracleValueInstruction,
} from "../instructions";

export const ORACCOUNT_PROGRAM_PROGRAM_ADDRESS =
  "BtrhqSTy1m3bZ687cZ1tPxNq2jNFhpEZXuJKaVimaFfN" as Address<"BtrhqSTy1m3bZ687cZ1tPxNq2jNFhpEZXuJKaVimaFfN">;

export enum OraccountProgramAccount {
  OracleAccount,
}

export function identifyOraccountProgramAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): OraccountProgramAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([189, 23, 49, 197, 79, 96, 245, 91]),
      ),
      0,
    )
  ) {
    return OraccountProgramAccount.OracleAccount;
  }
  throw new Error(
    "The provided account could not be identified as a oraccountProgram account.",
  );
}

export enum OraccountProgramInstruction {
  CreateOracleAccount,
  Initialize,
  UpdateOracleValue,
}

export function identifyOraccountProgramInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): OraccountProgramInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([15, 244, 56, 214, 148, 65, 100, 219]),
      ),
      0,
    )
  ) {
    return OraccountProgramInstruction.CreateOracleAccount;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([175, 175, 109, 31, 13, 152, 155, 237]),
      ),
      0,
    )
  ) {
    return OraccountProgramInstruction.Initialize;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([92, 44, 121, 72, 129, 49, 176, 37]),
      ),
      0,
    )
  ) {
    return OraccountProgramInstruction.UpdateOracleValue;
  }
  throw new Error(
    "The provided instruction could not be identified as a oraccountProgram instruction.",
  );
}

export type ParsedOraccountProgramInstruction<
  TProgram extends string = "BtrhqSTy1m3bZ687cZ1tPxNq2jNFhpEZXuJKaVimaFfN",
> =
  | ({
      instructionType: OraccountProgramInstruction.CreateOracleAccount;
    } & ParsedCreateOracleAccountInstruction<TProgram>)
  | ({
      instructionType: OraccountProgramInstruction.Initialize;
    } & ParsedInitializeInstruction<TProgram>)
  | ({
      instructionType: OraccountProgramInstruction.UpdateOracleValue;
    } & ParsedUpdateOracleValueInstruction<TProgram>);
