/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { ORACCOUNT_PROGRAM_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const CREATE_ORACLE_ACCOUNT_DISCRIMINATOR = new Uint8Array([
  15, 244, 56, 214, 148, 65, 100, 219,
]);

export function getCreateOracleAccountDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CREATE_ORACLE_ACCOUNT_DISCRIMINATOR,
  );
}

export type CreateOracleAccountInstruction<
  TProgram extends string = typeof ORACCOUNT_PROGRAM_PROGRAM_ADDRESS,
  TAccountOracle extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOracle extends string
        ? WritableAccount<TAccountOracle>
        : TAccountOracle,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CreateOracleAccountInstructionData = {
  discriminator: ReadonlyUint8Array;
  initValue: bigint;
};

export type CreateOracleAccountInstructionDataArgs = {
  initValue: number | bigint;
};

export function getCreateOracleAccountInstructionDataEncoder(): FixedSizeEncoder<CreateOracleAccountInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["initValue", getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: CREATE_ORACLE_ACCOUNT_DISCRIMINATOR,
    }),
  );
}

export function getCreateOracleAccountInstructionDataDecoder(): FixedSizeDecoder<CreateOracleAccountInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["initValue", getU64Decoder()],
  ]);
}

export function getCreateOracleAccountInstructionDataCodec(): FixedSizeCodec<
  CreateOracleAccountInstructionDataArgs,
  CreateOracleAccountInstructionData
> {
  return combineCodec(
    getCreateOracleAccountInstructionDataEncoder(),
    getCreateOracleAccountInstructionDataDecoder(),
  );
}

export type CreateOracleAccountAsyncInput<
  TAccountOracle extends string = string,
  TAccountAuthority extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  oracle?: Address<TAccountOracle>;
  authority: TransactionSigner<TAccountAuthority>;
  /** Sistema de programa para transferencias (si se necesita) */
  systemProgram?: Address<TAccountSystemProgram>;
  initValue: CreateOracleAccountInstructionDataArgs["initValue"];
};

export async function getCreateOracleAccountInstructionAsync<
  TAccountOracle extends string,
  TAccountAuthority extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ORACCOUNT_PROGRAM_PROGRAM_ADDRESS,
>(
  input: CreateOracleAccountAsyncInput<
    TAccountOracle,
    TAccountAuthority,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  CreateOracleAccountInstruction<
    TProgramAddress,
    TAccountOracle,
    TAccountAuthority,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? ORACCOUNT_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    oracle: { value: input.oracle ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.oracle.value) {
    accounts.oracle.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            111, 114, 97, 99, 108, 101, 95, 97, 99, 99, 111, 117, 110, 116,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.authority.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.oracle),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateOracleAccountInstructionDataEncoder().encode(
      args as CreateOracleAccountInstructionDataArgs,
    ),
    programAddress,
  } as CreateOracleAccountInstruction<
    TProgramAddress,
    TAccountOracle,
    TAccountAuthority,
    TAccountSystemProgram
  >);
}

export type CreateOracleAccountInput<
  TAccountOracle extends string = string,
  TAccountAuthority extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  oracle: Address<TAccountOracle>;
  authority: TransactionSigner<TAccountAuthority>;
  /** Sistema de programa para transferencias (si se necesita) */
  systemProgram?: Address<TAccountSystemProgram>;
  initValue: CreateOracleAccountInstructionDataArgs["initValue"];
};

export function getCreateOracleAccountInstruction<
  TAccountOracle extends string,
  TAccountAuthority extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ORACCOUNT_PROGRAM_PROGRAM_ADDRESS,
>(
  input: CreateOracleAccountInput<
    TAccountOracle,
    TAccountAuthority,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CreateOracleAccountInstruction<
  TProgramAddress,
  TAccountOracle,
  TAccountAuthority,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? ORACCOUNT_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    oracle: { value: input.oracle ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.oracle),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateOracleAccountInstructionDataEncoder().encode(
      args as CreateOracleAccountInstructionDataArgs,
    ),
    programAddress,
  } as CreateOracleAccountInstruction<
    TProgramAddress,
    TAccountOracle,
    TAccountAuthority,
    TAccountSystemProgram
  >);
}

export type ParsedCreateOracleAccountInstruction<
  TProgram extends string = typeof ORACCOUNT_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    oracle: TAccountMetas[0];
    authority: TAccountMetas[1];
    /** Sistema de programa para transferencias (si se necesita) */
    systemProgram: TAccountMetas[2];
  };
  data: CreateOracleAccountInstructionData;
};

export function parseCreateOracleAccountInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCreateOracleAccountInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      oracle: getNextAccount(),
      authority: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCreateOracleAccountInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
