/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { ORACCOUNT_PROGRAM_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const UPDATE_ORACLE_VALUE_DISCRIMINATOR = new Uint8Array([
  92, 44, 121, 72, 129, 49, 176, 37,
]);

export function getUpdateOracleValueDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_ORACLE_VALUE_DISCRIMINATOR,
  );
}

export type UpdateOracleValueInstruction<
  TProgram extends string = typeof ORACCOUNT_PROGRAM_PROGRAM_ADDRESS,
  TAccountOracle extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOracle extends string
        ? WritableAccount<TAccountOracle>
        : TAccountOracle,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateOracleValueInstructionData = {
  discriminator: ReadonlyUint8Array;
  newValue: bigint;
};

export type UpdateOracleValueInstructionDataArgs = {
  newValue: number | bigint;
};

export function getUpdateOracleValueInstructionDataEncoder(): FixedSizeEncoder<UpdateOracleValueInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["newValue", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: UPDATE_ORACLE_VALUE_DISCRIMINATOR }),
  );
}

export function getUpdateOracleValueInstructionDataDecoder(): FixedSizeDecoder<UpdateOracleValueInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["newValue", getU64Decoder()],
  ]);
}

export function getUpdateOracleValueInstructionDataCodec(): FixedSizeCodec<
  UpdateOracleValueInstructionDataArgs,
  UpdateOracleValueInstructionData
> {
  return combineCodec(
    getUpdateOracleValueInstructionDataEncoder(),
    getUpdateOracleValueInstructionDataDecoder(),
  );
}

export type UpdateOracleValueInput<
  TAccountOracle extends string = string,
  TAccountAuthority extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  oracle: Address<TAccountOracle>;
  authority: TransactionSigner<TAccountAuthority>;
  /** Sistema de programa para transferencias (si se necesita) */
  systemProgram?: Address<TAccountSystemProgram>;
  newValue: UpdateOracleValueInstructionDataArgs["newValue"];
};

export function getUpdateOracleValueInstruction<
  TAccountOracle extends string,
  TAccountAuthority extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ORACCOUNT_PROGRAM_PROGRAM_ADDRESS,
>(
  input: UpdateOracleValueInput<
    TAccountOracle,
    TAccountAuthority,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): UpdateOracleValueInstruction<
  TProgramAddress,
  TAccountOracle,
  TAccountAuthority,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? ORACCOUNT_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    oracle: { value: input.oracle ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.oracle),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getUpdateOracleValueInstructionDataEncoder().encode(
      args as UpdateOracleValueInstructionDataArgs,
    ),
    programAddress,
  } as UpdateOracleValueInstruction<
    TProgramAddress,
    TAccountOracle,
    TAccountAuthority,
    TAccountSystemProgram
  >);
}

export type ParsedUpdateOracleValueInstruction<
  TProgram extends string = typeof ORACCOUNT_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    oracle: TAccountMetas[0];
    authority: TAccountMetas[1];
    /** Sistema de programa para transferencias (si se necesita) */
    systemProgram: TAccountMetas[2];
  };
  data: UpdateOracleValueInstructionData;
};

export function parseUpdateOracleValueInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUpdateOracleValueInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      oracle: getNextAccount(),
      authority: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getUpdateOracleValueInstructionDataDecoder().decode(instruction.data),
  };
}
